//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmporioUP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analise_Perfil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Analise_Perfil()
        {
            this.Kit = new HashSet<Kit>();
        }
    
        public int id_perfil { get; set; }
        public string perfil { get; set; }
        public Nullable<int> fk_id_resposta { get; set; }
    
        public virtual Resposta Resposta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kit> Kit { get; set; }
    }
}
