//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmporioUP.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;

    public partial class Funcionario
    {
        public int id_funcionario { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string senha { get; set; }

        //This method validates the Login credentials
        public string LoginProcess(string strNome, string strSenha)
        {
            string message = "";
            //my connection string
            SqlConnection con = new SqlConnection("data source=RUAN\\SQLEXPRESS;initial catalog=msdb;integrated security=True;MultipleActiveResultSets=True;");
            SqlCommand cmd = new SqlCommand("Select * from Funcionario where nome =@nome", con);
            cmd.Parameters.AddWithValue("@nome", strNome);
            try
            {
                con.Open();
                SqlDataReader reader = cmd.ExecuteReader();
                if (reader.Read())
                {
                    bool login = (strSenha.Equals(reader["senha"].ToString(), StringComparison.InvariantCulture)) ? true : false;
                    if (login)
                    {
                        message = "1";
                        nome = reader["nome"].ToString();

                    }
                    else
                        message = "Login ou senha inválidos.";
                }
                else
                    message = "Login ou senha inválidos.";

                reader.Close();
                reader.Dispose();
                cmd.Dispose();
                con.Close();
            }
            catch (Exception ex)
            {
                message = ex.Message.ToString() + "Error.";

            }
            return message;
        }
    }
}
