//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmporioUP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kit
    {
        public int id_kit { get; set; }
        public int numero { get; set; }
        public string kit1 { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<int> fk_perfil { get; set; }
        public Nullable<int> fk_produto { get; set; }
    
        public virtual Analise_Perfil Analise_Perfil { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
