//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmporioUP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resposta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resposta()
        {
            this.Analise_Perfil = new HashSet<Analise_Perfil>();
        }
    
        public int id_resposta { get; set; }
        public string resposta1 { get; set; }
        public Nullable<int> fk_id_pergunta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Analise_Perfil> Analise_Perfil { get; set; }
        public virtual Pergunta Pergunta { get; set; }
    }
}
