//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmporioUP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public int id_venda { get; set; }
        public Nullable<int> fk_id_cliente { get; set; }
        public Nullable<int> fk_id_produto { get; set; }
        public int qtde { get; set; }
        public decimal valor { get; set; }
        public decimal total { get; set; }
        public System.DateTime dt_venda { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
